[pytest]
asyncio_mode = strict
# Установим scope по умолчанию на уровне функции
asyncio_default_fixture_loop_scope = function
asyncio_default_test_loop_scope = function

# Задаем таймаут для всех тестов
timeout = 10

# Настройки логгирования
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S