// This file is auto-generated by the run_services.sh script
// It contains the configuration for the frontend application

const config = {
  // API endpoints
  apiBaseUrl: 'http://localhost:8001',
  wsBaseUrl: 'ws://localhost:8001',
  
  // Service endpoints
  services: {
    aiCore: 'http://localhost:7876',
    developmentAgents: 'http://localhost:7876',
    projectManager: 'http://localhost:7876',
    cmp: 'http://localhost:7876',
    gitService: 'http://localhost:7876'
  }
};

export default config;
