// This file is auto-generated by the run_services.sh script
// It contains the configuration for the frontend application

const config = {
  // API endpoints
  apiBaseUrl: 'http://localhost:8000',
  wsBaseUrl: 'ws://localhost:8000',
  
  // Service endpoints
  services: {
    aiCore: 'http://localhost:7871',
    developmentAgents: 'http://localhost:7872',
    projectManager: 'http://localhost:7873',
    cmp: 'http://localhost:7874',
    gitService: 'http://localhost:7875'
  }
};

export default config;
