name: Documentation Update

on:
  push:
    branches: [ main, master ]
    paths:
      - 'ai-systems/**/*.py'
      - 'ai-systems/**/*.js'
      - 'ai-systems/**/*.jsx'
      - 'ai-systems/**/*.ts'
      - 'ai-systems/**/*.tsx'
      - 'docs/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'ai-systems/**/*.py'
      - 'ai-systems/**/*.js'
      - 'ai-systems/**/*.jsx'
      - 'ai-systems/**/*.ts'
      - 'ai-systems/**/*.tsx'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints myst-parser
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Generate Python API documentation
        run: |
          mkdir -p docs/api
          sphinx-apidoc -f -o docs/api ai-systems
          cd docs
          make html
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install JSDoc
        run: npm install -g jsdoc
      
      - name: Generate JavaScript API documentation
        run: |
          mkdir -p docs/js-api
          jsdoc -r ai-systems/web/frontend/src -d docs/js-api
      
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          destination_dir: docs
          commit_message: 'docs: update documentation [skip ci]'
      
      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: |
            docs/_build/html/
            docs/js-api/
          retention-days: 7
